### ISSUE TITLE
Apply BC Gov design system to application assessment automation

### ISSUE THREAD

**Issue by Nicole-Huard** [bcgov/devhub-app-web#1687] opened 2021-10-28 00:27 UTC
Pull in the province’s design system in to make the report look more official.  https://github.com/bcgov/design-system -- add header, footer and format tables according to the design system

DoD:
[ ] design system applied to improve the aesthetics of the application assessment report

**Comment by mitovskaol** [comment] 2021-11-02 23:59
Duplicate of [#1826](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1826)

**Closed by mitovskaol** 2021-11-02 23:59 UTC
