### ISSUE TITLE
Implement Application Assessment into SILVER cluster

### ISSUE THREAD

**Issue by Nicole-Huard** [bcgov/devhub-app-web#1688] opened 2021-10-28 20:07 UTC

**Comment by mitovskaol** [comment] 2021-11-02 23:59
Duplicate of [#1828](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1828)

**Closed by mitovskaol** 2021-11-02 23:59 UTC
