### ISSUE TITLE
Include disclaimer/statement around how we use brand logos in the Devhub.

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#342] opened 2019-01-30 19:21 UTC
Because we use non-gov brand logos in some areas of the DevHub, we should provide a discliamer/statement that indicates how we use these, who owns them (along the lines of "trademarks are the property of their respective owners"), and how to object/submit a request to remove, etc.

**Comment by patricksimonian** [comment] 2019-03-22 18:36
duplicate of #398

**Closed by patricksimonian** 2019-03-22 18:36 UTC
Labels: duplicate
