### ISSUE TITLE
Search UI should include a display of the *current search* perhaps combined with the "reset" mechanism

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#364] opened 2019-02-01 23:55 UTC
Upon performing a search, there is no indication *what* the search parameters were.  It's common to display some representation of the search parameters - whether *within* with search box as a "pill" (with an "X" to reset), or below/near the search box.

**Comment by patricksimonian** [comment] 2019-03-22 18:41
duplicate of #465

**Closed by patricksimonian** 2019-03-22 18:41 UTC
Labels: duplicate, task:ux/ui
